pipeline {
    agent any

    stages {        
        stage('Run script') {
            steps {
                sh "mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < B8.5/script.sql > output.txt"                
            }
        }
        stage('Print output') {
            steps {
                sh "sed -n '1,20p' output.txt"                
            }
        }              
    }
}