Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/bionic64"
  
    config.vm.provision "shell", path: "install.sh"

    config.vm.provision "file", source: "emptyfile", destination: "emptyfile"
  end
  