pipeline {
    agent any
    stages {
        stage('Build docker container') {
            steps {                
                sh 'docker build -t my-nginx ./PW8'
            }
        }
        stage('Run docker container') {
            steps {
                sh 'docker run -dp 9889:80 my-nginx'                
            }
        }
        stage('Check status code') {
            steps {
                sh 'echo HTTP status code: $(curl -o /dev/null -s -w "%{http_code}\\n" http://localhost:9889)'
                script {
                    env.HTTP_CODE = sh (
                        script: 'echo HTTP status code: $(curl -o /dev/null -s -w "%{http_code}\\n" http://localhost:9889)',
                        returnStdout: true
                    ).trim()
                }
            }
        }
        stage('Compare md5') {
            steps {
                dir('PW8') {
                    sh 'md5sum index.html > index.md5'
                    sh 'rm index.html'
                    sh 'wget -H http://localhost:9889/index.html'
                    sh 'md5sum -c index.md5'
                    script {
                        env.MD5 = sh (
                        script: 'md5sum -c index.md5',
                        returnStdout: true
                        ).trim()
                    }    
                }
            }
        }
        stage('Delete docker containers') {
            steps {
                sh 'docker rm -f $(docker ps -q)'
                sh 'docker rmi -f $(docker images -q)'
            }
        }
    }
    post{
        always{
            withCredentials([string(credentialsId: 'TELE_TOKEN', variable: 'TOKEN'), string(credentialsId: 'chat_ID', variable: 'CHAT_ID')]) {
                sh  ("""
                curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage \
                -d chat_id=${CHAT_ID} \
                -d parse_mode=markdown \
                -d text='*Job:* ${env.JOB_NAME}%0A*Branch*: ${env.GIT_BRANCH}%0A*Status*: `${currentBuild.currentResult}`%0A*Detail:*%0A*MD5 check*: ${env.MD5}%0A*HTTP status code:* ${env.HTTP_CODE}'
                """)
            }
        }       
    }
}