pipeline {
    agent any
    stages {
        stage('Build docker container') {
            steps {                
                sh 'docker build --build-arg BUILD_ID -t my-nginx ./PW8'
            }
        }
        stage('Run docker container') {
            steps {
                sh 'docker run -dp 9889:80 my-nginx'                
            }
        }
        stage('Check status code') {
            steps {
                sh 'echo HTTP status code: $(curl -o /dev/null -s -w "%{http_code}\\n" http://localhost:9889)'
            }
        }
        stage('Compare md5') {
            steps {
                echo "====++++MD5++++===="
            }
        }
        stage('Delete docker containers') {
            steps {
                sh 'docker image prune --filter label=stage=builder --filter label=build=$BUILD_ID'
            }
        }
    }
}